/**
 * OpenIdProviderConfiguration Names
 * http://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata
 */
export const OpenIdProviderMetadataNames = {
  AcrValuesSupported: "acr_values_supported",
  AuthorizationEndpoint: "authorization_endpoint",
  CheckSessionIframe: "check_session_iframe",
  ClaimsLocalesSupported: "claims_locales_supported",
  ClaimsParameterSupported: "claims_parameter_supported",
  ClaimsSupported: "claims_supported",
  ClaimTypesSupported: "claim_types_supported",
  Discovery: ".well-known/openid-configuration",
  DisplayValuesSupported: "display_values_supported",
  EndSessionEndpoint: "end_session_endpoint",
  FrontchannelLogoutSessionSupported: "frontchannel_logout_session_supported",
  FrontchannelLogoutSupported: "frontchannel_logout_supported",
  HttpLogoutSupported: "http_logout_supported",
  GrantTypesSupported: "grant_types_supported",
  IdTokenEncryptionAlgValuesSupported: "id_token_encryption_alg_values_supported",
  IdTokenEncryptionEncValuesSupported: "id_token_encryption_enc_values_supported",
  IdTokenSigningAlgValuesSupported: "id_token_signing_alg_values_supported",
  IntrospectionEndpoint: "introspection_endpoint",
  IntrospectionEndpointAuthMethodsSupported: "introspection_endpoint_auth_methods_supported",
  IntrospectionEndpointAuthSigningAlgValuesSupported: "introspection_endpoint_auth_signing_alg_values_supported",
  JwksUri: "jwks_uri",
  Issuer: "issuer",
  LogoutSessionSupported: "logout_session_supported",
  MicrosoftMultiRefreshToken: "microsoft_multi_refresh_token",
  OpPolicyUri: "op_policy_uri",
  OpTosUri: "op_tos_uri",
  RegistrationEndpoint: "registration_endpoint",
  RequestObjectEncryptionAlgValuesSupported: "request_object_encryption_alg_values_supported",
  RequestObjectEncryptionEncValuesSupported: "request_object_encryption_enc_values_supported",
  RequestObjectSigningAlgValuesSupported: "request_object_signing_alg_values_supported",
  RequestParameterSupported: "request_parameter_supported",
  RequestUriParameterSupported: "request_uri_parameter_supported",
  RequireRequestUriRegistration: "require_request_uri_registration",
  ResponseModesSupported: "response_modes_supported",
  ResponseTypesSupported: "response_types_supported",
  ServiceDocumentation: "service_documentation",
  ScopesSupported: "scopes_supported",
  SubjectTypesSupported: "subject_types_supported",
  TokenEndpoint: "token_endpoint",
  TokenEndpointAuthMethodsSupported: "token_endpoint_auth_methods_supported",
  TokenEndpointAuthSigningAlgValuesSupported: "token_endpoint_auth_signing_alg_values_supported",
  UILocalesSupported: "ui_locales_supported",
  UserInfoEndpoint: "userinfo_endpoint",
  UserInfoEncryptionAlgValuesSupported: "userinfo_encryption_alg_values_supported",
  UserInfoEncryptionEncValuesSupported: "userinfo_encryption_enc_values_supported",
  UserInfoSigningAlgValuesSupported: "userinfo_signing_alg_values_supported",
};
